# Называем worlflow
name: pw test
# Когда запускать тесты
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 
# Сама джоба
jobs: 
 test:
  timeout-minutes: 60
# Задаем окружение
  runs-on: ubuntu-latest
  steps: 
   - uses: actions/checkout@4
   - uses: actions/setup-node@4
     with: 
      node-version: lts/*
   - run: npm i   
   - name: install PW
     run: npx playwright install --with-deps
   - name: run test
     run: npm run test
# Сохраняем отчет pw  
   - uses: actions/upload-artifact@4
     if: always()
     continue-on-error: true
     with:
      name: test-results
      path: test-results 
      retentions-days: 20
 # Сохраняем отчет allure
   - uses: actions/upload-artifact@4
     if: always()
     continue-on-error: true
     with:
      name: allure-results
      path: allure-results
      retentions-days: 20
# Забираем результаты предыдущего запуска отчеты allure
   - uses: actions/checkout@4
     if: always()
     continue-on-error: true
     with:
      ref: gh-pages
      path: gh-pages
# Формируем из allure резалт отчет
   - uses: simple-elf/allure-report-action@master
     if: always()
     id: allure-report
     with:
      allure_results: build/allure-results
      gh_pages: gh-pages
      allure_report: allure-report
      allure_history: allure-history
      keep-reports: 20

# Деплоим отчет
   - name: Деплоим отчет
     if: always()
     uses: peaceiris/actions-gh-pages@v2
     env:
      PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PUBLISH_BRANCH: gh-pages
      PUBLISH_DIR: allure-history
    
       
     
  

  
    
